language: java
# os: [osx, linux]
env:
  global:
    # This is a convenience variable for shortening download commands
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
  matrix:
  - JDK="adopt@1.12"
  - JDK="adopt-openj9@1.12"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
services:
- mysql
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output ~/.clean_gradle_cache.sh
  - bash ~/.clean_gradle_cache.sh
before_install:
- echo "127.0.0.1"       > CBI/src/main/resources/credentials.txt
- echo "3306"           >> CBI/src/main/resources/credentials.txt
- echo "root"           >> CBI/src/main/resources/credentials.txt
- echo ""               >> CBI/src/main/resources/credentials.txt
- echo ""               >> CBI/src/main/resources/credentials.txt
- echo ""               >> CBI/src/main/resources/credentials.txt
- echo "conversational" >> CBI/src/main/resources/credentials.txt
- openssl aes-256-cbc -K $encrypted_c124cbaf5663_key -iv $encrypted_c124cbaf5663_iv -in ./CBI/resources/sql/dump.sql.enc -out ./CBI/resources/sql/dump.sql -d
- mysql -u root < CBI/resources/sql/dump.sql
- mysql -e 'use conversational; select * from queries limit 5;'
script:
- cd CBI
- chmod +x gradlew
- "./gradlew -i"
deploy:
  provider: releases
  api_key:
    secure: BujVztYzlbaGdm0QFJW06bUOfEahoheRWAuYEdtalBmxPSBSgMyAohghtuSdZe3lDLIBCJvMJsRUBsX0X1pz+emAqYTqRuBOFlz01T3S9///bSgPvJLrTpYhECqa3TAiA0MOUGZAZxbKqFbMhfLHLCh8JI5xYK7n50RR7Z5KMOpa0hOmIv3toDQNOG3jTZwrHjkXeDxLxwvNfeKVgDoCxG5t2zx8YS9y+rFiMpmoZKSvT+QzmFDrhy/uMhn4XbG1zh1jpDvSCqJa379vxtnTK4ARodhrm2Zr0O500rmnFQeyj19J62yx4LR3wEEhi1eyfUSKlK46a/ruBRwlo79U7KTUirzoq2wPDS5DCKS1+6phFeqiALCf2DU+2Gxrc5MvgshTqlteYpVVHwDqKLG1Y1FuSqkPxcx4f3h0FGxRRkhFy9/DUxBzdDAg6aAGHEZe6eaHpBBBRpALlyh+2rWfAhDXQN7+DI7VdFqg1k8OfpOlHMWqcGIRlvKU5L0HWdQXBASGieJQToYeue1mZAbIBRRADrR2tn0oYVdABwVhxnqbwlllZsob6XKisSNs5Kw32Lci0/mo6qZFtvjIIaLdEXKHtckKJgGH3ocxfjzwJImaVyGDAVPIhFK7D/S4C/Ai++bNpb+ZAyuQ8HptZY3j9Uijm22ADr0KvCsZybNqB1c=
  file: CBI/build/libs/conversational-all.jar
  on:
    repo: w4bo/CBI
